# -*- coding: utf-8 -*-
"""
Nudged Elastic Band (NEB) driver for vasp-mace.

Supports:
  Plain NEB:      LCLIMB = .FALSE. (default)
  Climbing-image: LCLIMB = .TRUE.  (CI-NEB)

  SPRING sets the spring constant k = |SPRING| eV/Å² in both cases.

Note on LCLIMB:
  LCLIMB is *not* a native VASP tag.  It is borrowed from the VTST Tools
  (https://theory.cm.utexas.edu/vtsttools/neb.html), which extend VASP with
  the climbing-image algorithm.  Native VASP (without VTST) does not recognise
  LCLIMB and always runs plain NEB.  vasp-mace follows the VTST convention so
  that INCAR files written for VTST-enabled VASP work without modification.

Input layout (VASP convention):
  00/POSCAR   — reactant endpoint  (fixed)
  01/POSCAR   — intermediate image 1  (optional; IDPP-interpolated when absent)
  …
  NN/POSCAR   — product endpoint  (fixed)   NN = IMAGES + 1

Output (per image directory):
  CONTCAR, OUTCAR, OSZICAR, vasprun.xml

Shared output:
  ase_files/neb_opt.log   — optimizer log
  ase_files/mace.traj     — ASE trajectory (all intermediate images, all steps)
"""

from __future__ import annotations

import os
import time
import numpy as np

# NEB: prefer modern ase.mep, fall back to older ase.neb
try:
    from ase.mep import NEB
except ImportError:
    from ase.neb import NEB  # type: ignore[no-redef]

from ase.optimize import BFGS, FIRE, LBFGS, MDMin
from ase.io.trajectory import Trajectory

from .logging_utils import StepLogger, StepRecord
from .io_vasp import (
    read_poscar,
    write_contcar,
    write_outcar,
    write_oszicar,
    write_relax_vasprun_xml,
    write_single_vasprun_xml,
)
from .mace_loader import load_calc
from .types_ import IncarConfig

ASE_OUT_DIR = "ase_files"


# -----------------------------------------------------------------------
# Input reading
# -----------------------------------------------------------------------

def _read_neb_images(n_images: int) -> tuple[list, bool]:
    """Load endpoint and (optionally) intermediate POSCARs.

    Parameters
    ----------
    n_images : int
        Number of *intermediate* images (INCAR tag IMAGES).

    Returns
    -------
    images : list of ase.Atoms, length n_images + 2
        Endpoints are fully loaded. Intermediate images are either loaded from
        disk or copied from image 00 as placeholders for IDPP interpolation.
    interpolate : bool
        True when intermediate POSCARs were absent (caller must interpolate).
    """
    n_total = n_images + 2

    for idx in (0, n_total - 1):
        p = os.path.join(f"{idx:02d}", "POSCAR")
        if not os.path.isfile(p):
            raise FileNotFoundError(
                f"Endpoint POSCAR not found: {p}\n"
                f"NEB expects directories 00/ through {n_total - 1:02d}/, "
                f"each containing a POSCAR."
            )

    # Require all-or-nothing intermediate POSCARs (partial paths are ambiguous)
    inter_present = [
        os.path.isfile(os.path.join(f"{i:02d}", "POSCAR"))
        for i in range(1, n_total - 1)
    ]
    if any(inter_present) and not all(inter_present):
        missing = [f"{i:02d}/POSCAR" for i, ok in enumerate(inter_present, 1) if not ok]
        raise FileNotFoundError(
            f"Partial NEB path detected. Missing: {missing}\n"
            "Either provide ALL intermediate POSCARs or NONE "
            "(absent images are generated by IDPP interpolation)."
        )

    interpolate = not any(inter_present)
    endpoint_0 = read_poscar(os.path.join("00", "POSCAR"))
    endpoint_N = read_poscar(os.path.join(f"{n_total - 1:02d}", "POSCAR"))

    images = [endpoint_0]
    for i in range(1, n_total - 1):
        if interpolate:
            images.append(endpoint_0.copy())  # placeholder; overwritten by neb.interpolate()
        else:
            images.append(read_poscar(os.path.join(f"{i:02d}", "POSCAR")))
    images.append(endpoint_N)

    # Validate species consistency across images
    ref_symbols = endpoint_0.get_chemical_symbols()
    for i, img in enumerate(images[1:], 1):
        if img.get_chemical_symbols() != ref_symbols:
            raise ValueError(
                f"Image {i:02d} has species {img.get_chemical_symbols()} "
                f"but image 00 has {ref_symbols}. All images must have the same atoms."
            )

    return images, interpolate


# -----------------------------------------------------------------------
# Output writing
# -----------------------------------------------------------------------

def _write_image_outputs(
    img_dir: str,
    image,
    atoms_initial,
    steps: list[StepRecord],
    is_endpoint: bool,
    incar_raw: dict,
    converged: bool,
    elapsed: float,
    cpu_t: float,
) -> None:
    """Write CONTCAR, OUTCAR, OSZICAR, vasprun.xml into img_dir/."""
    os.makedirs(img_dir, exist_ok=True)

    write_contcar(os.path.join(img_dir, "CONTCAR"), image)
    write_oszicar(os.path.join(img_dir, "OSZICAR"), steps)
    write_outcar(
        os.path.join(img_dir, "OUTCAR"),
        image,
        steps,
        incar_raw=incar_raw,
        converged=converged,
        elapsed=elapsed,
        cpu_time=cpu_t,
    )

    if is_endpoint or len(steps) <= 1:
        # Single-point style: endpoint or image that never moved
        rec = steps[0]
        write_single_vasprun_xml(
            os.path.join(img_dir, "vasprun.xml"),
            image,
            forces=rec.forces,
            stress=rec.stress,
            energy=rec.energy,
            incar_raw=incar_raw,
        )
    else:
        # Relaxation style: shows full ionic-step history for the image
        write_relax_vasprun_xml(
            os.path.join(img_dir, "vasprun.xml"),
            atoms_initial,
            image,
            steps,
            incar_raw=incar_raw,
        )


# -----------------------------------------------------------------------
# NEB driver
# -----------------------------------------------------------------------

def run_neb(
    cfg: IncarConfig,
    model_path: str,
    device: str = "auto",
    dtype: str = "auto",
    dispersion: bool = False,
    optimizer: str = "BFGS",
) -> tuple[list[list[StepRecord]], bool]:
    """Run a NEB calculation.

    Reads images from 00/POSCAR … {IMAGES+1:02d}/POSCAR.
    Writes CONTCAR, OUTCAR, OSZICAR, vasprun.xml into each image directory.

    Parameters
    ----------
    cfg : IncarConfig
        INCAR configuration. Uses IMAGES, SPRING, NSW, EDIFFG, IBRION, IVDW.
    model_path : str
        Path to the MACE .model file.
    device, dtype : str
        Passed to load_calc (device/dtype resolved on first call).
    dispersion : bool
        Enable DFT-D3 dispersion correction.
    optimizer : str
        Fallback optimizer name {BFGS, FIRE, LBFGS} when IBRION is not in INCAR.

    Returns
    -------
    image_steps : list[list[StepRecord]], length = IMAGES + 2
        Endpoint lists contain one StepRecord each (frozen single-point).
        Intermediate image lists contain one StepRecord per ionic step.
    converged : bool
    """
    n_images = cfg.IMAGES
    if n_images < 1:
        raise ValueError(f"IMAGES={n_images}: NEB requires at least 1 intermediate image.")

    climb = cfg.LCLIMB
    k = abs(cfg.SPRING)
    n_total = n_images + 2

    # Convergence: force-based for NEB (EDIFFG < 0 is standard; > 0 is ambiguous)
    if cfg.EDIFFG < 0:
        f_tol = abs(cfg.EDIFFG)
    else:
        f_tol = float(cfg.EDIFFG) if cfg.EDIFFG > 0 else 0.05
        print(f"[warn] NEB: EDIFFG={cfg.EDIFFG} ≥ 0; using as force tolerance (eV/Å).")

    # ---- Read images --------------------------------------------------------
    images, do_interpolate = _read_neb_images(n_images)

    # ---- Attach one independent calculator per image (ASE requirement) ------
    # Resolve device/dtype once; reuse for all subsequent images.
    calc_0, device, dtype = load_calc(
        model_path, device=device, dtype=dtype, dispersion=dispersion
    )
    images[0].calc = calc_0
    for i in range(1, n_total):
        calc_i, _, _ = load_calc(model_path, device=device, dtype=dtype, dispersion=dispersion)
        images[i].calc = calc_i

    print(
        f"[info] NEB: Model={model_path}, device={device}, dtype={dtype}, "
        f"IMAGES={n_images}, k={k:.3f} eV/Å², "
        f"{'CI-NEB' if climb else 'NEB'}, NSW={cfg.NSW}, EDIFFG={cfg.EDIFFG}"
    )

    # ---- Evaluate endpoints before NEB construction -------------------------
    # This primes the endpoint calculator caches. ASE NEB ('aseneb' method)
    # does not re-evaluate endpoints during the band optimisation, so these
    # cached values remain valid and consistent throughout.
    t0_wall = time.time()
    t0_cpu  = time.process_time()

    E_start = images[0].get_potential_energy()
    F_start = images[0].get_forces()

    E_end = images[-1].get_potential_energy()
    F_end = images[-1].get_forces()

    ep_logger_start = StepLogger()
    ep_logger_start.log(n=1, energy=E_start, forces=F_start, atoms=images[0])

    ep_logger_end = StepLogger()
    ep_logger_end.log(n=1, energy=E_end, forces=F_end, atoms=images[-1])

    print(f"[NEB] E(00)={E_start:.6f} eV | E({n_total-1:02d})={E_end:.6f} eV")

    # ---- Build NEB and interpolate if needed --------------------------------
    neb = NEB(images, k=k, climb=climb)
    if do_interpolate:
        neb.interpolate(method='idpp')
        print(f"[NEB] Interpolated {n_images} intermediate image(s) using IDPP.")

    # Snapshot initial geometries of intermediate images (before optimisation)
    atoms_initials = [images[i].copy() for i in range(1, n_total - 1)]

    # ---- Optimizer ----------------------------------------------------------
    # MDMin is the recommended optimizer for NEB. Its velocity projection step
    # (v ← f * (v·f)/|f|²) keeps v always aligned with the NEB force; when
    # spring forces rotate between steps (non-conservative), v·f goes negative
    # and velocity is reset to zero, preventing the Hessian corruption (BFGS)
    # or runaway velocity (FIRE) that causes divergence for NEB.
    #
    # IBRION mapping for NEB:
    #   1 (quasi-Newton / RMM-DIIS in VASP) → MDMin (robust NEB default)
    #   2 (CG in VASP)                       → MDMin
    #   3 (damped MD in VASP)                → FIRE
    #   CLI --optimizer flag                 → respected if IBRION absent
    os.makedirs(ASE_OUT_DIR, exist_ok=True)

    if "IBRION" in cfg.raw:
        _ibrion_map = {1: "MDMIN", 2: "MDMIN", 3: "FIRE"}
        opt_name = _ibrion_map.get(cfg.IBRION, "MDMIN")
    else:
        opt_name = (optimizer or "MDMIN").upper()
    Optim = {"BFGS": BFGS, "FIRE": FIRE, "LBFGS": LBFGS, "MDMIN": MDMin}.get(opt_name, MDMin)

    # maxstep=0.01 Å (20× smaller than ASE default of 0.2 Å). The default
    # causes catastrophic overshoots near tight NEB transition-state geometries
    # (a 0.2 Å step can push atoms into near-overlap, spiking forces to
    # 5+ eV/Å and corrupting BFGS Hessians or FIRE velocities).
    # With 0.01 Å each atom's per-step displacement is safely below the
    # ~0.5 Å buffer to nearest neighbours, and the MDMin oscillation amplitude
    # near convergence stays below the EDIFFG force threshold.
    dyn = Optim(neb, logfile=os.path.join(ASE_OUT_DIR, "neb_opt.log"), maxstep=0.01)

    # Per-image step loggers (intermediate images only)
    image_loggers = [StepLogger() for _ in range(n_images)]

    # ---- NEB optimisation loop ----------------------------------------------
    # Mirrors run_relax: one ionic step at a time, explicit force evaluation
    # after each step so logging reflects forces at the post-step geometry.
    converged = False

    for n in range(1, cfg.NSW + 1):
        dyn.run(fmax=f_tol, steps=1)

        # After dyn.run(steps=1) image positions have changed. Call neb.get_forces()
        # explicitly to evaluate forces at the new geometry. This call:
        #   (a) triggers MACE on all intermediate images (endpoint calcs are cached),
        #   (b) populates neb.energies[1:-1],
        #   (c) returns the projected NEB forces used for convergence.
        neb_forces_flat = neb.get_forces()  # shape (n_images*natoms, 3)
        fmax_opt = float(np.max(np.linalg.norm(neb_forces_flat, axis=1)))

        # Log per-image real (unprojected) forces from calculator caches
        energies_inter = []
        for j, img_idx in enumerate(range(1, n_total - 1)):
            img = images[img_idx]
            E_i = img.get_potential_energy()  # cached; no extra evaluation
            F_i = img.get_forces()            # cached; no extra evaluation
            image_loggers[j].log(n=n, energy=E_i, forces=F_i, atoms=img)
            energies_inter.append(E_i)

        emax = max(energies_inter)
        imax = int(np.argmax(energies_inter)) + 1  # 1-based index in full images list
        barrier = emax - E_start

        print(
            f"[NEB step {n}] Fmax={fmax_opt:.3f} eV/Å | "
            f"Emax={emax:.6f} eV (image {imax:02d}) | "
            f"barrier={barrier:.4f} eV"
        )

        if fmax_opt <= f_tol:
            converged = True
            break

    # Write the final NEB band as a trajectory: one frame per image, reactant → product.
    traj_path = os.path.join(ASE_OUT_DIR, "mace.traj")
    traj = Trajectory(traj_path, "w")
    for img in images:
        traj.write(img)
    traj.close()

    elapsed = time.time()        - t0_wall
    cpu_t   = time.process_time() - t0_cpu

    # ---- Write per-image VASP output files ----------------------------------
    _write_image_outputs(
        img_dir="00",
        image=images[0],
        atoms_initial=images[0],
        steps=ep_logger_start.steps,
        is_endpoint=True,
        incar_raw=cfg.raw,
        converged=True,
        elapsed=elapsed,
        cpu_t=cpu_t,
    )

    for j, img_idx in enumerate(range(1, n_total - 1)):
        _write_image_outputs(
            img_dir=f"{img_idx:02d}",
            image=images[img_idx],
            atoms_initial=atoms_initials[j],
            steps=image_loggers[j].steps,
            is_endpoint=False,
            incar_raw=cfg.raw,
            converged=converged,
            elapsed=elapsed,
            cpu_t=cpu_t,
        )

    _write_image_outputs(
        img_dir=f"{n_total - 1:02d}",
        image=images[-1],
        atoms_initial=images[-1],
        steps=ep_logger_end.steps,
        is_endpoint=True,
        incar_raw=cfg.raw,
        converged=True,
        elapsed=elapsed,
        cpu_t=cpu_t,
    )

    # Assemble return value: [endpoint_0_steps, img1_steps, …, endpoint_N_steps]
    all_steps = (
        [ep_logger_start.steps]
        + [lg.steps for lg in image_loggers]
        + [ep_logger_end.steps]
    )
    return all_steps, converged
